version: "3.7"
services:
  ta-db:
    image: mongo:4.0
    restart: always
    expose:
      - "27017"
  ta-parser:
    image: ${PARSER_IMAGE}
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    depends_on:
      - ta-db
  ta-backend:
    image: ${BACKEND_IMAGE}
    restart: always
    expose:
      - "5000"
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    depends_on:
      - ta-db
  ta-frontend:
    image: ${FRONTEND_IMAGE}
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - ta-backend
