version: "3.7"
services:
  ta-index:
    image: elasticsearch:7.5.1
    expose:
      - "9200"
    environment:
      - discovery.type=single-node
  ta-parser:
    image: ${PARSER_IMAGE}
    environment:
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_INDEX=${ELASTIC_INDEX}
    depends_on:
      - ta-index
  ta-backend:
    image: ${BACKEND_IMAGE}
    restart: always
    expose:
      - "5000"
    environment:
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_INDEX=${ELASTIC_INDEX}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    depends_on:
      - ta-index
  ta-frontend:
    image: ${FRONTEND_IMAGE}
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - ta-backend
